spring.application.name=deploy004_springboot

# TODO 포트 유의사항
# 사용되고 있지 않은 포트 선정
# ubuntu 22.04의 서버에서 8080(tomcat), 8181(jenkins)
# Dockerfile 작성할 때 Expose 9090 해줘야한다
# docker run -d -p 8383:9090 [이미지이름] => 포트를 조심해라
server.port=9090